# ========================================
# IoT Gateway Service 配置 - iot-gateway-service.yaml
# Data ID: iot-gateway-service.yaml
# Group: DEFAULT_GROUP
# Namespace: dev
# ========================================

spring:
  datasource:
    url: jdbc:mysql://${datasource.host}:${datasource.port}/nova_x_iot?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai
    username: ${datasource.username}
    password: ${datasource.password}
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid: ${datasource.druid}

  redis:
    host: ${redis.host}
    port: ${redis.port}
    database: 5
    password: ${redis.password}
    timeout: ${redis.timeout}
    lettuce: ${redis.lettuce}

  kafka:
    bootstrap-servers: ${kafka.bootstrap-servers}
    producer: ${kafka.producer}
    consumer: ${kafka.consumer}
    # IoT 特定配置
    topics:
      device-data: device-data-topic
      device-command: device-command-topic
      device-status: device-status-topic
